stock_market/stock_info/urls.py
from django.conf.urls import url
from stock_info import views
from django.urls import path, include


app_name = 'stock_info'

urlpatterns = [
    #url(r'^$', views.stock_index, name = 'stock_index'),
    #url(r'^stock_info/', include('stock_info.urls')),
]

stock_market/stock_market/urls.py
from django.contrib import admin
from django.urls import path, include
from user_info import views
from django.conf.urls import url, include
from stock_info.views import StockListView, stock_list_view, StockDetailView, stock_detail_view


urlpatterns = [
    path('admin/', admin.site.urls),


    url(r'^$', views.index, name='index'),


    url(r'^user_info/', include('user_info.urls')),


    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'special/', views.special, name='special'),



    url(r'^stock/$', StockListView.as_view(), name = 'StockListView'),
    url(r'^stock-fbv/$', stock_list_view),




    url(r'^stock/(?P<pk>\d+)/$', StockDetailView.as_view()),
    url(r'^stock-fbv/(?P<pk>\d+)/$', stock_detail_view),



]

stock_market/user_info/urls.py
from django.conf.urls import url
from user_info import views
from django.urls import path, include


app_name = 'user_info'

urlpatterns = [


    url(r'^register/$', views.register, name = 'register'),
    #path('user_info/', include('user_info.url'))
    url(r'^user_login/$', views.user_login,name='user_login')


]

stock_market/stock_info/models.py
from django.db import models
import django.db.models.fields
from user_info.models import UserProfileInfo
from django.conf.urls import url, include

#from .views import StockDetailView


# Create your models here.

class StockInfo(models.Model):

    symbol = models.CharField(max_length=10)
    date = models.DateField()
    high = models.DecimalField(max_digits=15, decimal_places=7, null=True)
    low = models.DecimalField(max_digits=15, decimal_places=7, null=True)
    open = models.DecimalField(max_digits=15, decimal_places=7, null=True)
    close = models.DecimalField(max_digits=15, decimal_places=7, null=True)
    volume = models.DecimalField(max_digits=15, decimal_places=2, null=True)
    adj_close = models.DecimalField(max_digits=15, decimal_places=7, null=True)
    #user = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE)#




    def get_absolute_url(self):
        return ("{}".format(self.id))

    def __str__(self):
        return self.symbol

stock_market/user_info/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.



class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)#DO_NOTHING)


    #portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)
    balance = models.DecimalField (max_digits=10, decimal_places=2, validators=[MinValueValidator(1000),
                                       MaxValueValidator(99999)], default=1000)

    def __str__(self):
        return self.user.username

stock_market/user_info/forms.py
from django import forms
from django.contrib.auth.models import User
from user_info.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('profile_pic','balance')

stock_market/stock_info/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.views.generic import TemplateView, ListView, DetailView
from .models import StockInfo
from django.http import HttpResponse


# Create your views here.



class StockListView(ListView):
    queryset = StockInfo.objects.all()
    template_name = "stock_info/stock_list_view.html"


    def get_context_data(self, *args, **kwargs):
        context = super(StockListView, self).get_context_data(*args, **kwargs)
        print(context)
        return context


def stock_list_view(request):
    queryset = StockInfo.objects.all()
    context = {
        'object_list' : queryset
    }
    return render(request, "stock_info/stock_list_view.html", context)









class StockDetailView(DetailView):
    queryset = StockInfo.objects.all()
    template_name = "stock_info/stock_detail_view.html"


    def get_context_data(self, *args, **kwargs):
        context = super(StockDetailView, self).get_context_data(*args, **kwargs)
        print(context)
        return context





def stock_detail_view(request, pk= None, *args, **kwargs):

    #instance = get_object_or_404(StockInfo, pk=pk)
    try:
        instance = StockInfo.objects.get (id =pk)
    except StockInfo.DoesNotExist:
        #print("This stock are not available")
        raise Http404("Stock doesn't exist")
    except:
        print("Sorry")

    context = {
        'object': instance
    }

    return render(request, "stock_info/stock_detail_view.html", context)

stock_market/user_info/views.py
from django.shortcuts import render
from user_info.forms import UserForm, UserProfileInfoForm


from django.urls import reverse
#from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout




# Create your views here.
def index(request):
    return render(request, 'user_info/index.html')




@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))




@login_required
def special(request):
    return HttpResponse("You are Logged In 👍 ")


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)


        if user_form.is_valid() and profile_form.is_valid():
            user = user_form. save()
            user.set_password(user.password)
            user.save()



            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'user_info/registration.html',
                    {'user_form':user_form,
                     'profile_form': profile_form,
                     'registered': registered})




def user_login (request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')


        user = authenticate(username = username, password= password)


        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Not registered")

        else:
            print("Someone tried to login and failed")
            print("Username: {} and Password {}".format(username,password))
            return HttpResponse("Invalid login details supplied")

    else:
        return render(request, 'user_info/login.html',{})

stock_market/templates/stock_info/stock_base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

<nav class = 'navbar navbar-default navbar-static-top'>




</nav>




</body>
</html>

stock_market/templates/stock_info/stock_detail_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stock Detail View</title>
</head>
<body>


<div class="container">
     <div class="jumbotron">




<h3>Stock Name: {{object.symbol}}</h3>



         <p>Date: {{object.date}}</p>
         <p>High: {{object.high}}</p>
         <p>Low: {{object.low}}</p>
         <p>Open: {{object.open}}</p>
         <p>Close: {{object.close}}</p>
         <p> Volume: {{object.volume}}</p>
         <p> Adjust Close: {{object.adj_close}}</p>



    </div>
    </div>

</body>
</html>

stock_market/templates/stock_info/stock_list_view.html
<!DOCTYPE html>
{% include 'stock_info/stock_base.html'%}

<html lang="en">
<head>
    <meta charset="UTF-8">

</head>
<body>


<div class="container">

     <div class="jumbotron">

         <h3> Stock Name: </h3>

            {% for object in object_list%}

                {% include 'stock_info/snippets.html' %}


                    <a href="{{ object.get_absolute_url }}" >
                        {{object.symbol}}<br>


                    </a>
{%endfor%}
    </div>
    </div>

</body>
</html>

stock_market/templates/user_info/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

<nav class = 'navbar navbar-default navbar-static-top'>
    <div class="container">

        <ul class = "nav navbar-nav">
            <li>
                <a class = "navbar-brand" href="{%url 'index'%}"> Homepage </a>
            </li>

            <li>
                <a class="navbar-link" href="{% url 'admin:index' %}"> Admin </a>
            </li>

             <li>
             <a class="navbar-link" href="{% url 'user_info:register'%}"> Registration </a>
            </li>








            {% if user.is_authenticated %}


            <li>
                <a class="navbar-link" href="{% url 'logout' %}"> Logout </a>
            </li>



            <li>
                <a class = "navbar-brand" href="{% url 'StockListView' %}"> <h6>Stock List </h6> </a>

            </li>



            {% else %}
            <li>
                <a class="navbar-link" href="{% url 'user_info:user_login' %}"> Login </a>
            </li>
            {% endif %}



        </ul>
    </div>



</nav>

<div class="container">


{% block body_block %}
    {% endblock %}
</div>


</body>
</html>

stock_market/templates/user_info/index.html
<!DOCTYPE html>
{% extends "user_info/base.html" %}

{% block body_block%}

<div class="jumbotron">
    <h1> <center>Welcome to my Stock Market Website</center></h1>
</div>
{% endblock %}

stock_market/templates/user_info/login.html
{% extends 'user_info/base.html' %}

{%block body_block%}
<div class="jumbotron">
    <h1>Please Login Here 👇 </h1>
    <form action="{% url 'user_info:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username"> Username: </label>
    <input type="text" name="username" placeholder="Enter Username">



    <label for="password"> Password: </label>
    <input type="password" name="password">


    <input type="submit" name="" value="Login">

    </form>


</div>

{% endblock %}

stock_market/templates/user_info/registration.html
<!DOCTYPE html>
{% extends "user_info/base.html" %}
{% load staticfiles%}
{% block body_block%}

<div class="jumbotron">

    {% if registered %}
    <h1> Thank you for registration </h1>
       {% else %}

    <h1> Register Here</h1>
    <h3> Fill up the form</h3>


    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <input type="submit" name="" value="Register">

    </form>

    {% endif %}

</div>
{% endblock%}